#!/bin/bash
# SOCKS5 Proxy (Dante) Manager for AlmaLinux 10
# Install, uninstall, manage users, view logs, configure whitelist.
#
# Usage:
#   ./socks5.sh                        Interactive install
#   ./socks5.sh -uninstall             Remove Dante and config
#   ./socks5.sh -adduser USER PASS     Add proxy user
#   ./socks5.sh -deluser USER          Delete proxy user
#   ./socks5.sh -log [N]               Show last N log lines (default 50)
#   ./socks5.sh -whitelist=CIDR        Replace whitelist with new CIDR list
#
# Examples:
#   ./socks5.sh -whitelist=1.2.3.4/32
#   ./socks5.sh -whitelist=1.2.3.0/24:5.6.7.8/32

set -e

# --- Global paths (resolved dynamically) ---
SERVICE_NAME=""
CONF_FILE=""
LOG_FILE="/var/log/sockd.log"

# --- Helper: resolve service name and config path ---
resolve_service() {
    SERVICE_NAME=""
    for svc in sockd danted; do
        if systemctl list-unit-files 2>/dev/null | grep -q "^${svc}\.service"; then
            SERVICE_NAME="$svc"
            break
        fi
    done
    if [[ -z "$SERVICE_NAME" ]]; then
        for f in /usr/lib/systemd/system/sockd.service /usr/lib/systemd/system/danted.service; do
            if [[ -f "$f" ]]; then
                SERVICE_NAME=$(basename "$f" .service)
                break
            fi
        done
    fi
    [[ -z "$SERVICE_NAME" ]] && SERVICE_NAME="sockd"

    CONF_FILE=""
    local unit_file
    unit_file=$(systemctl cat "$SERVICE_NAME" 2>/dev/null | grep -E "^ExecStart" | head -n1)
    if [[ "$unit_file" =~ -f[[:space:]]+([^[:space:]]+) ]]; then
        CONF_FILE="${BASH_REMATCH[1]}"
    fi
    if [[ -z "$CONF_FILE" ]]; then
        if [[ -f /etc/sockd.conf ]]; then
            CONF_FILE="/etc/sockd.conf"
        else
            CONF_FILE="/etc/danted.conf"
        fi
    fi
}

# --- Helper: detect external interface ---
detect_iface() {
    local iface
    iface=$(ip route show default | awk '/default/ {print $5}' | head -n 1)
    [[ -z "$iface" ]] && iface="eth0"
    echo "$iface"
}

# --- Helper: ensure user exists (for unprivileged) ---
ensure_unprivileged_user() {
    local conf="$1"
    local u
    u=$(grep -E "^user\.unprivileged:" "$conf" | awk '{print $2}' | head -n1)
    if [[ -n "$u" ]] && ! id "$u" &>/dev/null; then
        echo "[!] User '$u' does not exist. Creating it."
        useradd -r -s /sbin/nologin "$u"
    fi
}

# =========================================================
# ACTION: INSTALL (interactive)
# =========================================================
do_install() {
    echo "=== SOCKS5 Proxy (Dante) Installer for AlmaLinux 10 ==="
    echo ""

    read -p "SOCKS5 port (default: 1080): " PORT
    PORT=${PORT:-1080}

    read -p "Username for authentication: " PROXY_USER
    while [[ -z "$PROXY_USER" ]]; do
        echo "Username cannot be empty."
        read -p "Username: " PROXY_USER
    done

    read -s -p "Password for $PROXY_USER: " PROXY_PASS
    echo ""
    while [[ -z "$PROXY_PASS" ]]; do
        echo "Password cannot be empty."
        read -s -p "Password: " PROXY_PASS
        echo ""
    done

    echo ""
    echo "----------------------------------------"
    echo "Port:     $PORT"
    echo "User:     $PROXY_USER"
    echo "Password: ******"
    echo "----------------------------------------"
    read -p "Correct? (y/N): " CONFIRM
    if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi

    echo ""
    echo "[*] Installing required packages..."
    dnf install -y epel-release
    if ! dnf install -y dante-server; then
        echo ""
        echo "==================================================================="
        echo "ERROR: 'dante-server' package not found."
        echo "AlmaLinux 10 does not ship it in standard/EPEL repos yet."
        echo "Options: third-party repo (GetPageSpeed) or compile from source."
        echo "==================================================================="
        exit 1
    fi

    resolve_service
    echo "[+] Service: $SERVICE_NAME"
    echo "[+] Config:  $CONF_FILE"

    echo ""
    echo "[*] Creating authentication user..."
    if id "$PROXY_USER" &>/dev/null; then
        echo "[!] User '$PROXY_USER' exists. Updating password..."
        echo "$PROXY_USER:$PROXY_PASS" | chpasswd
    else
        useradd -r -s /sbin/nologin "$PROXY_USER"
        echo "$PROXY_USER:$PROXY_PASS" | chpasswd
        echo "[+] User '$PROXY_USER' created."
    fi

    local EXTERNAL_IFACE
    EXTERNAL_IFACE=$(detect_iface)
    echo "[*] External interface: $EXTERNAL_IFACE"

    echo ""
    echo "[*] Writing configuration to $CONF_FILE..."
    [[ -f "$CONF_FILE" ]] && cp "$CONF_FILE" "${CONF_FILE}.bak.$(date +%s)"

    cat > "$CONF_FILE" <<EOF
# Dante SOCKS5 configuration - generated by socks5.sh
logoutput: $LOG_FILE

internal: 0.0.0.0 port = $PORT
external: $EXTERNAL_IFACE

socksmethod: username
clientmethod: none

user.privileged: root
user.unprivileged: $PROXY_USER

client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: error connect disconnect
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    command: connect
    log: error connect disconnect
}
EOF

    touch "$LOG_FILE"
    chown "$PROXY_USER":"$PROXY_USER" "$LOG_FILE" 2>/dev/null || true
    chmod 644 "$LOG_FILE"

    echo ""
    echo "[*] Starting service $SERVICE_NAME..."
    systemctl enable "$SERVICE_NAME" &>/dev/null || true
    systemctl restart "$SERVICE_NAME"
    sleep 1

    if systemctl is-active --quiet "$SERVICE_NAME"; then
        echo "[+] Service is running."
    else
        echo "[!] Service failed to start. Check:"
        echo "    journalctl -u $SERVICE_NAME -n 50 --no-pager"
        exit 1
    fi

    echo ""
    echo "[*] Configuring firewall..."
    if systemctl is-active --quiet firewalld; then
        firewall-cmd --permanent --add-port=$PORT/tcp >/dev/null
        firewall-cmd --reload >/dev/null
        echo "[+] Port $PORT/tcp opened."
    else
        echo "[!] firewalld not running. Open port $PORT/tcp manually."
    fi

    echo ""
    echo "[*] Verifying listener on port $PORT..."
    if ss -tlnp 2>/dev/null | grep -q ":$PORT "; then
        echo "[+] Port $PORT is LISTENING."
    else
        echo "[!] Port $PORT not in LISTEN. Check log:"
        echo "    tail -n 30 $LOG_FILE"
    fi

    local IP_PUBLIC
    IP_PUBLIC=$(curl -s --max-time 5 https://ifconfig.me || echo "<SERVER_IP>")
    echo ""
    echo "==================================================================="
    echo "SOCKS5 Proxy installed successfully."
    echo "==================================================================="
    echo ""
    echo "  Server:   $IP_PUBLIC"
    echo "  Port:     $PORT"
    echo "  User:     $PROXY_USER"
    echo "  Config:   $CONF_FILE"
    echo "  Service:  $SERVICE_NAME"
    echo "  Log:      $LOG_FILE"
    echo ""
    echo "Test:"
    echo "  curl --socks5-basic -u $PROXY_USER:PASSWORD -x socks5://$IP_PUBLIC:$PORT https://ifconfig.me"
    echo ""
    echo "Management:"
    echo "  $0 -adduser USER PASS"
    echo "  $0 -deluser USER"
    echo "  $0 -log 100"
    echo "  $0 -whitelist=1.2.3.4/32"
    echo "  $0 -uninstall"
    echo "==================================================================="
}

# =========================================================
# ACTION: UNINSTALL
# =========================================================
do_uninstall() {
    echo "=== Uninstalling Dante SOCKS5 Proxy ==="
    resolve_service

    read -p "This will remove Dante and its configuration. Continue? (y/N): " C
    if [[ ! "$C" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi

    echo "[*] Stopping and disabling service..."
    systemctl stop "$SERVICE_NAME" 2>/dev/null || true
    systemctl disable "$SERVICE_NAME" 2>/dev/null || true

    echo "[*] Removing package..."
    dnf remove -y dante-server 2>/dev/null || true

    echo "[*] Removing configuration and logs..."
    rm -f /etc/sockd.conf /etc/danted.conf
    rm -f /etc/sockd.conf.bak.* /etc/danted.conf.bak.* 2>/dev/null || true
    rm -f "$LOG_FILE"

    echo "[*] Closing firewall ports..."
    if systemctl is-active --quiet firewalld; then
        for p in $(firewall-cmd --list-ports 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+/tcp$'); do
            local pn="${p%/tcp}"
            # Heuristic: only close ports that were probably opened by us
            if ss -tlnp 2>/dev/null | grep -q ":$pn "; then
                continue
            fi
            firewall-cmd --permanent --remove-port="$p" >/dev/null 2>&1 || true
        done
        firewall-cmd --reload >/dev/null 2>&1 || true
    fi

    echo ""
    echo "[+] Uninstall complete."
    echo "    Note: authentication users you created were NOT removed."
    echo "    Remove them manually if needed: userdel <username>"
}

# =========================================================
# ACTION: ADD USER
# =========================================================
do_adduser() {
    local u="$1"
    local p="$2"
    if [[ -z "$u" || -z "$p" ]]; then
        echo "Usage: $0 -adduser USERNAME PASSWORD"
        exit 1
    fi
    if id "$u" &>/dev/null; then
        echo "[!] User '$u' exists. Updating password..."
        echo "$u:$p" | chpasswd
    else
        useradd -r -s /sbin/nologin "$u"
        echo "$u:$p" | chpasswd
        echo "[+] User '$u' created."
    fi
}

# =========================================================
# ACTION: DELETE USER
# =========================================================
do_deluser() {
    local u="$1"
    if [[ -z "$u" ]]; then
        echo "Usage: $0 -deluser USERNAME"
        exit 1
    fi
    if ! id "$u" &>/dev/null; then
        echo "[!] User '$u' does not exist."
        exit 1
    fi
    userdel "$u" 2>/dev/null || true
    echo "[+] User '$u' removed."
}

# =========================================================
# ACTION: SHOW LOG
# =========================================================
do_log() {
    local n="${1:-50}"
    if [[ ! -f "$LOG_FILE" ]]; then
        echo "[!] Log file $LOG_FILE does not exist."
        resolve_service
        # Try journalctl as fallback
        echo "[*] Falling back to journalctl -u $SERVICE_NAME"
        journalctl -u "$SERVICE_NAME" -n "$n" --no-pager
        exit 0
    fi
    echo "[*] Last $n lines of $LOG_FILE:"
    tail -n "$n" "$LOG_FILE"
}

# =========================================================
# ACTION: WHITELIST
# =========================================================
do_whitelist() {
    local wl="$1"
    if [[ -z "$wl" ]]; then
        echo "Usage: $0 -whitelist=CIDR[:CIDR...]"
        echo "Example: $0 -whitelist=1.2.3.4/32"
        echo "         $0 -whitelist=1.2.3.0/24:5.6.7.8/32"
        exit 1
    fi

    resolve_service
    if [[ ! -f "$CONF_FILE" ]]; then
        echo "[!] Config file $CONF_FILE not found. Is Dante installed?"
        exit 1
    fi

    # Convert ':' separated list into Dante 'from: a to: b' syntax
    # Dante allows: from: { 1.2.3.4/32, 5.6.7.8/32 } to: 0.0.0.0/0
    local cidrs
    cidrs=$(echo "$wl" | tr ':' ',')
    # Sanitize: strip spaces
    cidrs=$(echo "$cidrs" | tr -d ' ')

    echo "[*] Updating whitelist in $CONF_FILE..."
    cp "$CONF_FILE" "${CONF_FILE}.bak.$(date +%s)"

    # Remove any existing client pass block and insert new one
    # We use awk to replace the first 'client pass { ... }' block.
    awk -v cidrs="$cidrs" '
        BEGIN { replaced=0; inblock=0 }
        /^client pass \{/ && !replaced {
            print "client pass {"
            print "    from: { " cidrs " } to: 0.0.0.0/0"
            print "    log: error connect disconnect"
            print "}"
            replaced=1
            inblock=1
            next
        }
        inblock {
            if (/^\}/) { inblock=0 }
            next
        }
        { print }
    ' "$CONF_FILE" > "${CONF_FILE}.tmp" && mv "${CONF_FILE}.tmp" "$CONF_FILE"

    echo "[*] Restarting service..."
    systemctl restart "$SERVICE_NAME"
    sleep 1
    if systemctl is-active --quiet "$SERVICE_NAME"; then
        echo "[+] Whitelist updated. Service running."
    else
        echo "[!] Service failed to start after whitelist update. Restoring backup..."
        local latest_bak
        latest_bak=$(ls -t "${CONF_FILE}".bak.* 2>/dev/null | head -n1)
        if [[ -n "$latest_bak" ]]; then
            cp "$latest_bak" "$CONF_FILE"
            systemctl restart "$SERVICE_NAME" 2>/dev/null || true
            echo "[!] Restored from $latest_bak"
        fi
        exit 1
    fi
}

# =========================================================
# MAIN DISPATCH
# =========================================================
case "${1:-}" in
    -uninstall)
        do_uninstall
        ;;
    -adduser)
        do_adduser "$2" "$3"
        ;;
    -deluser)
        do_deluser "$2"
        ;;
    -log)
        do_log "$2"
        ;;
    -whitelist=*)
        do_whitelist "${1#-whitelist=}"
        ;;
    -h|--help)
        grep -E "^#" "$0" | sed 's/^# \?//' | head -n 20
        ;;
    "")
        do_install
        ;;
    *)
        echo "Unknown option: $1"
        echo "Run '$0 --help' for usage."
        exit 1
        ;;
esac
